# Quarkus Base Configuration
# 
# This file contains the base configuration for a Quarkus application.
# Please define the properties that are common to all environments here.
# For environment-specific configurations, and it is not a private value, please use the following:
# - development environment:
#     - application-dev.yaml for development-specific preference
#     - .env for secret values on development environment
# - production environment:
#     - server/manifests/application.yaml for production-specific non-secret overrides on Kubernetes
#     - server/manifests/application-secret-template.yaml as the template for secret config file keys
#        - create the actual secret-only config file out-of-band and mount it as application-secret.yaml
#        - when you add a secret value, please also add its key to server/manifests/application-secret-template.yaml
#     - do never write actual secret values to tracked files. Instead, use secret resources.
#     - mount production config files under /deployments/config on Kubernetes


quarkus:
  datasource:
    db-kind: postgresql
    # username: ""
    # password: ""
    # jdbc:
    #   url: ""

  flyway:
    enabled: true
    locations: "classpath:db/migration"
    migrate-at-start: true
    schemas: public

  smallrye-openapi:
    path: /openapi
    info-title: "VAGINA Server API"
    info-version: 0.0.1

  swagger-ui:
    path: /swagger-ui
    always-include: true

  smallrye-health:
    root-path: /healthz

  http:
    cors:
      enabled: true
      origins: /.*/
      headers: accept,authorization,content-type,x-requested-with
      exposed-headers: authorization,content-type
      methods: GET,POST,PUT,DELETE,OPTIONS
      access-control-allow-credentials: true
      access-control-max-age: 24H
    
  log: {} # configure down level

  websockets-next:
    server:
      max-frame-size: 1048576
      max-message-size: 1048576
    
  micrometer:
    enabled: true
    export:
      prometheus:
        enabled: true
        path: /q/metrics
    binder:
      http-server:
        enabled: true
      http-client:
        enabled: true
      vertx:
        enabled: true
      jvm:
        enabled: true

mybatis:
  environment:
    id: quarkus
  

vagina:
  auth:
    access-token: 
      lifespan: 3600
    refresh-token:
      lifespan: 2592000
    oauth:
      state:
        lifespan: 600
      pkce:
        secret: null
    oidc:
      redirect-uri:
        web: ""
        mobile: ""
        desktop: ""

  realtime: {} # configure down level
  text-agent: {} # configure down level
  object-storage: {}



