apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vagina-server

resources:
  - backend.yaml
  - jwt-keys.yaml
  - ingress.yaml
  - db.yaml

configMapGenerator:
  - name: backend-config
    files:
      - application.yaml

images:
  - name: ghcr.io/yuki-js/vagina-server
    newTag: latest-native

labels:
  - pairs:
      app: vagina-server
